# Generated by Django 4.1.6 on 2023-02-26 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название книги')),
                ('text', models.TextField(verbose_name='Краткое содержание')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('img', models.ImageField(default='books/image/default.png', upload_to='books/image/', verbose_name='Фото')),
                ('author_fn', models.CharField(default='Без имени', max_length=255, verbose_name='Имя автора')),
                ('author_ln', models.CharField(default='Без фамилии', max_length=255, verbose_name='Фамилия автора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
                'ordering': ('created_on',),
            },
        ),
    ]
